# =================================================================
# CrazyAra's Configuration File
# ------------------------------
# CrazyAra, a deep learning chess variant engine
# Copyright (C) 2018 Johannes Czech, Moritz Willig, Alena Beyer
# Copyright (C) 2019 Johannes Czech
#
# CrazyAra is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# @file: config.yaml
# Created on 27.06.2019
# @author: queensgambit
#
# This file contains the configuration for different path of the
# CrazyAra engine.
#
# =================================================================
# 
# The model directory contains the architecture definition (.json) 
# as well as the weights of the neural network (.params). 
model_directory: /home/queensgambit/Programming/Deep_Learning/CrazyAra_Fish/model/
#
